// <auto-generated />
namespace AgileProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MovieRatingForeignKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieRatingForeignKey));
        
        string IMigrationMetadata.Id
        {
            get { return "202111101351130_MovieRatingForeignKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
